title: Graziele M. Mazuco dos Santos # your name (or website title) here
#logo: "/images/picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data professional with over 10 years of industry experience manipulating data, business intelligence analysis, and data analysis. Passionate about transforming data into insights that support decision making. 
  <br><br>
  <a href="https://www.linkedin.com/in/graziele-mazuco/">View My LinkedIn Profile</a> <br>
  <a href="https://grazimazuco.medium.com/">View My Medium Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-QC1FL5HZ2E # your Google Analytics tracking ID here
